# Generated by Django 5.0.4 on 2024-08-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
    ]
