version: '3.8'

services:
  nginx:
    build: ./nginx 
    ports:
      - "1337:80"
    depends_on:
      - web
      - daphne
    volumes:
      - media_volume:/usr/src/app/media
  
  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - daphne 
  daphne:
    build: .
    command: daphne --bind 0.0.0.0 -p 8002 mysite.asgi:application
    ports:
      - "8002:8002"

volumes:
  media_volume:
